Repository dusk-network/rusk-schema, pull requests merged in 2020-09, with the labels that each got.

#3 Bid & BlindBid service basic implementations
  basic_fields.proto
  bid.proto
  blindbid.proto
  echo.proto
  keys.proto
  proto_tmp/rusk.proto
  rusk.proto
  transaction.proto
Labels: area:IPC, type:feature

#9 Add missing semicolons
  bid.proto
  transaction.proto
Labels: type:bug

#6 Fix typos & review secret_k usage
  bid.proto
Labels: area:IPC

#14 Remove rusk dependency from bid.proto
  bid.proto
Labels: area:IPC, type:bug

#16 Fix PoseidonCipher typos across protos
  bid.proto
  transaction.proto
Labels: area:IPC, type:bug

#17 Rename Bid secret_k parameter
  bid.proto
  blindbid.proto
  transaction.proto
Labels: area:IPC, type:refactor

#19 Fix compilation errs
  bid.proto
  blindbid.proto
  echo.proto
  rusk.proto
  transaction.proto
Labels: area:IPC, type:bug, type:tech-debt

#10 Add `go_package` option to all proto files
  basic_fields.proto
  bid.proto
  blindbid.proto
  echo.proto
  keys.proto
  rusk.proto
  transaction.proto
Labels: type:tech-debt

#22 Add simple service for keys
  keys.proto
Labels: area:IPC, type:feature

#23 Add state transition messages and functions
  rusk.proto
Labels: area:IPC, type:feature

#24 Add call and messages for fetching provisioners
  rusk.proto
Labels: area:IPC, type:feature

#26 Fix go_package option
  basic_fields.proto
  bid.proto
  blindbid.proto
  echo.proto
  keys.proto
  rusk.proto
  transaction.proto
Labels: area:IPC, type:bug

#28 Add services for creating a Transfer and Stake tx
  bid.proto
  stake.proto
  transfer.proto
Labels: area:IPC, area:tx, type:feature

#31 Add endpoints and messages for Staking service
  basic_fields.proto
  stake.proto
Labels: area:IPC, area:block-validation, type:feature

#33 Add imports for missing files to rusk.proto
  rusk.proto
Labels: area:IPC, type:bug

#34 Revert "Add imports for missing files to rusk.proto"
  rusk.proto
Labels: area:IPC, type:bug

#35 Add missing imports to rusk.proto
  rusk.proto
  stake.proto
Labels: area:IPC, type:bug

#37 Change Note message to correspond to phoenix-core Note
  transaction.proto
Labels: area:IPC, area:tx, type:refactor
